- name: play from variable
  hosts: localhost 
  vars:
  - course: Devops
    trainer: Rajesh 
    Duration: 600hrs 
  tasks:
    - name: play from play1
      ansible.builtin.debug:
        msg: "welcome to {{ course }} learning from trainer {{ Rajesh }} duration is {{ duration }}"
    