- name: play from variable
  hosts: localhost 
  vars:
    course: "Devops"
    trainer: "Rajesh" 
    Duration: "600hrs" 
  tasks:
    - name: check variables 
      ansible.builtin.debug:
        msg: "welcome to {{ course }} learning  trainer trainer  {{ Rajesh }} duration is {{ duration }}"
     