- name: condition 
  hosts: localhost
  become: yes
  tasks:
  - name: check robo shop user exist or not 
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true 

  - name: print and check robosho 
    ansible.builtin.debug:
      msg: "user output is : {{user}}"

  - name: print and check robosho 
    ansible.builtin.debug:
      msg: "status is  : {{user.rc}}"

  - name: create user 
    ansible.builtin.user:
      name: roboshop
    when: user.rc != 0
