# Condition in Ansible 
- name: condition 
  hosts: localhost
  tasks:
    - name: check if roboshop user exists
      ansible.builtin.command: id roboshop 
      register: User 

    - name: print variable value 
      ansible.builtin.debug:
        msg: "user output is: {{ User }}" 
