# loops in ansible 
- name: loops 
  hosts: localhost
  become: yes
  tasks:
    - name: install 
      ansible.builtin.package:
        msg: "{{ item }}"
      loop:
      - git  
      - mysql 
      - java 
      
