---
- name: Update web servers
  hosts: all
  become: yes

  tasks:
  - name: Ensure system update
    ansible.builtin.apt:
      update_cache: true
              

  - name: Ensure nginx present 
    ansible.builtin.apt:
      name: nginx
      state: present
